source "https://github.com/CocoaPods/Old-Specs"
#source "https://github.com/CocoaPods/Specs"

platform :ios, '6.0'
target "BarrageRendererDemo" do
    pod 'BarrageRenderer', '2.1.0'
    pod 'MLEmojiLabel', '1.0.0'
end
